title: JWX Toolkit for Go
theme: jekyll-theme-dinky
github:
  repository_url: https://github.com/lestrrat-go/jwx
  is_project_page: true
  is_user_page: false
  owner_url: https://github.com/lestrrat
  owner_name: Daisuke Maki (lestrrat)
